/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module fa_35 (
    input a,
    input b,
    input ci,
    output reg co,
    output reg s
  );
  
  
  
  always @* begin
    s = a ^ b ^ ci;
    co = (a & b) | ((a ^ b) & ci);
  end
endmodule
