/*
   This file was generated automatically by Alchitry Labs version 1.2.7.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SHIFT = 1
*/
module x_bit_left_shifter_26 (
    input [15:0] a,
    input pad,
    input shift,
    output reg [15:0] out
  );
  
  localparam SHIFT = 1'h1;
  
  
  integer i;
  
  reg [15:0] shifted_bits;
  
  wire [(5'h10+0)-1:0] M_mux32_out;
  reg [(5'h10+0)-1:0] M_mux32_s0;
  reg [(5'h10+0)*2-1:0] M_mux32_in;
  
  genvar GEN_mux320;
  generate
  for (GEN_mux320=0;GEN_mux320<5'h10;GEN_mux320=GEN_mux320+1) begin: mux32_gen_0
    mux_2_36 mux32 (
      .s0(M_mux32_s0[GEN_mux320*(1)+(1)-1-:(1)]),
      .in(M_mux32_in[GEN_mux320*(2'h2)+(2'h2)-1-:(2'h2)]),
      .out(M_mux32_out[GEN_mux320*(1)+(1)-1-:(1)])
    );
  end
  endgenerate
  
  always @* begin
    
    case (1'h1)
      4'h8: begin
        shifted_bits = {a[0+7-:8], {4'h8{pad}}};
      end
      3'h4: begin
        shifted_bits = {a[0+11-:12], {3'h4{pad}}};
      end
      2'h2: begin
        shifted_bits = {a[0+13-:14], {2'h2{pad}}};
      end
      1'h1: begin
        shifted_bits = {a[0+14-:15], {1'h1{pad}}};
      end
      default: begin
        shifted_bits = a;
      end
    endcase
    for (i = 1'h0; i < 5'h10; i = i + 1) begin
      M_mux32_in[(i)*2+0+0-:1] = a[(i)*1+0-:1];
      M_mux32_in[(i)*2+1+0-:1] = shifted_bits[(i)*1+0-:1];
      M_mux32_s0[(i)*1+0-:1] = shift;
    end
    out = M_mux32_out;
  end
endmodule
